### ISSUE TITLE
openapi.json file request to include `servers` and `scheme` attributes in public instance https://onion.ail-project.org/ to enable more flexible use

### ISSUE THREAD

**Issue by alexandercronin** [ail-project/onion-lookup#1]
## Details
The current public instance of this service[https://onion.ail-project.org/] provides a [onion-lookup.json](https://onion.ail-project.org/apiman/specification/) file. With some additions to this spec file the public instance could be used with more tool in a more flexible manner.

## Suggested additions to this specification file: 
1) Include a `servers` section in the spec.
    - benefit: the spec file can be used directly within a number of application to make requests directly to the public instance 
```
"servers": [
    {
      "url": "https://onion.ail-project.org"
    }
  ],
```

2) include a `schema` in the `parameters` section of each path definition
    - benefits: 
        - the spec file more closely adheres to the standard 
        - can be used directly with a number of tool which require type validation to render execution enabled docs e.g. [OpenAPI-Explorer](https://www.npmjs.com/package/openapi-explorer) to the public instance 

```
             "parameters":[
                {
                   "name":"onion",
                   "in":"path",
                   "required":true,    
                   "schema": {
                    "type": "string"
                  }
                }
             ],
```

Example openapi spec file which includes these features. [onion-lookup.json](https://github.com/user-attachments/files/17291742/onion-lookup.json)

**Comment by adulau** [comment]
Thanks a lot for the feedback. Super useful. I quickly fixed - 97b21b874ea5ab2bf9164479188b389cc5ce1168 - it and updated the [online service](https://onion.ail-project.org/apiman/specification/).

If you see anything else, don't hesitate to reopen the issue.

**Comment by alexandercronin** [comment]
Thanks for the quick response. Pleasure working with you:)

I think the server definition needs to be an array as opposed to a single entry to meet the scheme standard i.e.

this :
``` 
"servers":[ 
    {
      "url": "https://onion.ail-project.org"
    }
  ],
```
instead of the current value: 
```
"servers": {
    "url": "https://onion.ail-project.org"
  },
```
There is an online validator which gives feedback on adherence to the spec here: https://editor-next.swagger.io/. Currently it will auto convert your json to yaml. If I find a directonline json validator I will share it here. Most that I local installs.

**Comment by adulau** [comment]
Thanks for the feedback. It seems ok now from a validator perspective.

![Screenshot from 2024-10-13 11-47-07](https://github.com/user-attachments/assets/38ff8ad4-ff4f-451a-a3f9-11f2ec8b73bd)

and by the way, thanks for the hint to https://editor-next.swagger.io/ which is quite nice for generating client or server code out-of-the-box.

**Comment by alexandercronin** [comment]
Sorry for the delay. Working great now! |Thank you :)
